### ISSUE TITLE
Custom bash completion script

### ISSUE THREAD

**Issue by davidcollins4481** [CantonLinux/cantonlinux.org#18]
Ever curious about how autocomplete works in bash (or zsh)? Let's' create a custom bash completion script!

**Comment by meffie** [comment]
Nice topic!

**Comment by meffie** [comment]
Dave will do this one in Feb

**Comment by meffie** [comment]
Moved this one to March, per Davids message on slack.

**Comment by meffie** [comment]
Accepted for March 30, 2023.

Dave, can you provide a brief description for cantonlinux.org and meetup.com when you have a chance?

**Comment by davidcollins4481** [comment]
Surrrre. 

Learn the basics of bash completion by creating a basic completion script for an existing program. 

That work?

**Comment by meffie** [comment]
Yes, thanks!
