### ISSUE TITLE
Newer CLI tools

### ISSUE THREAD

**Issue by ghost** [CantonLinux/cantonlinux.org#20]
This talk will provide a basic introduction to a slew of newer CLI tools including bat, exa, fd, fzf, hexyl, hyperfine, pass, ripgrep, tealdeer, vivid, and zoxide with a special guest appearance by Mike Meffie covering taskwarrior.

**Comment by meffie** [comment]
Moved this one to Feb per conversation on slack.

**Comment by meffie** [comment]
Talk given on 2/23/2023 at Milestone. Thank you @sean-mac-dubhsithe 

Link provided by Sean https://programoires.gitlab.io/grimoires/cli/newer-cli-tools.html.

**Comment by meffie** [comment]
Link added the Feb 2023 talk post on cantonlinux.org
