### ISSUE TITLE
Let's use PAM to create two-factor authentication into a Linux server

### ISSUE THREAD

**Issue by meffie** [CantonLinux/cantonlinux.org#28]
David

**Comment by meffie** [comment]
Schedule for August 31, 2023

**Comment by meffie** [comment]
@davidcollins4481 Can you provide a title and description for the meeting notice?

**Comment by davidcollins4481** [comment]
Let's use PAM (Pluggable Authentication Modules) to create two-factor authentication into a Linux server

**Comment by davidcollins4481** [comment]
@meffie finally added this 😆

**Comment by meffie** [comment]
I opened this issue on Jan 26, just forgot to add @davidcollins4481 as participant :)
0h, nevermind, I get it now.

**Comment by davidcollins4481** [comment]
yeah that was all me

**Comment by meffie** [comment]
@davidcollins4481 are you still ok to give this talk on August 31st? If so, I'll update meetup.com and cantonlinux.org.

**Comment by meffie** [comment]
Talk given on August 31, 2023. Thanks David!
