### ISSUE TITLE
Introduction to Elixir Functional Programming Language

### ISSUE THREAD

**Issue by dwarner** [CantonLinux/cantonlinux.org#32]
Elixir is a functional programming language built on top or Erlang. 

If you love piping at the Linux command line, you are going to love Elixir!

I will demonstrate the differences between an object oriented language like Ruby, to a functional programming language like Elixir.

The talk will go over Elixir collection types, piping, pattern matching and recursion.

**Comment by meffie** [comment]
Thanks @dwarner!  We currently have an open slot on July 27, 2023. Are you available?

**Comment by dwarner** [comment]
@meffie Sounds good, Mike. Please add me to the schedule for July.

**Comment by meffie** [comment]
Scheduled for July 27, 2023. Thanks Dennis!

https://www.cantonlinux.org/schedule.html

**Comment by meffie** [comment]
Talk completed.
